### ISSUE TITLE
Naming of sitemap directory is wrong

### ISSUE THREAD

**Issue by nwootton** [kubawolanin/generator-openhab#11]
Nice utility - great for skeletonising new installations. Minor issue though.

Generating a new OH2 using this Yeoman generator resulted in 3 directories (as expected):

- html
- items
- sitemap

Actual name of directory should be sitemap**s**.

**Comment by kubawolanin** [comment]
Hey @nwootton thank you for reporting!

The fix should be really easy - it's a matter of changing the path [in this line](https://github.com/kubawolanin/generator-openhab/blob/master/generators/app/index.js#L332).

EDIT: I'll publish a new npm package soon so the fix is available for everyone. Thanks again!
